### ISSUE TITLE
Abstract and re-use object policy comparison

### ISSUE THREAD

**Issue by depombo** [iasql/iasql-engine#1077]
AWS does not return arrays within the JSON policy in a deterministic order so a deep equality is not sufficient here which made https://github.com/iasql/iasql-engine/pull/1074 necessary. We should do this for every JSON or policy that AWS gives us

**Comment by dfellis** [comment]
What will kinda suck about this is I bet we'll eventually run across some JSON blob from the AWS API that *does* care about array order, and then we'll need an exception to this exception.

**Comment by depombo** [comment]
Part of https://github.com/iasql/iasql-engine/issues/1117
