### ISSUE TITLE
Investigate Localstack for local dev

### ISSUE THREAD

**Issue by depombo** [iasql/iasql-engine#1080]
https://localstack.cloud what is the API. can we just get credentials from them?

**Comment by depombo** [comment]
https://reflectoring.io/aws-localstack/

**Comment by depombo** [comment]
Ideally we can get credentials from Localstack and the interface into our test suite doesn't change which are environment variables with the AWS keys https://github.com/iasql/iasql-engine/blob/main/test/modules/aws-ec2-integration.ts

**Comment by dfellis** [comment]
We'll probably (ab)use the `AWS_REGION` environment variable inside of the AWS SDK logic to swap out the server they talk to with `Localstack`, once that's figured out.

**Comment by mtp1376** [comment]
TLDR;
- `pip install localstack`
- `localstack start`
- `pip install 'awscli-local[ver1]'` -> to be able to use `awslocal` command
- `localstack status` & `localstack status services`
- `awslocal sqs create-queue --queue-name sample-queue`

**Comment by dfellis** [comment]
@mtp1376 are there any examples of how to use it with the [AWS JS SDK](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/)? If we want to substitute this into our local testing, we need a way to convince that to talk to it.

**Comment by dfellis** [comment]
https://qubyte.codes/blog/tip-connecting-to-localstack-s3-using-the-javascript-aws-sdk-v3 it looks like you just need to specify `endpoint: 'http://localhost:4566',` to have the SDK talk to localstack.

**Comment by mtp1376** [comment]
- What changes are necessary to run the tests on our local system?
- We should have an easy switch between AWS and LocalStack for our test suite
- What services are not covered in the LocalStack

**Comment by depombo** [comment]
It might help to take a look at https://github.com/iasql/iasql-engine/blob/main/CONTRIBUTING.md to answer the first question

**Comment by mtp1376** [comment]
By injecting the `endpoint` value in any of the AWS clients, we can make IaSQL request LocalStack instead of actual AWS.
`src/services/aws_macros.ts:65`:
```node.js
    this.ec2client = new EC2({
      region: "us-east-2",
      credentials: {
        accessKeyId: "XXX",
        secretAccessKey: "YYY",
      },
      endpoint: 'http://172.21.0.4:4566',
    });
```

After trying to run `SELECT * FROM iasql_apply();`, received this error:
```
Query 1 ERROR: ERROR:  APPLY error: "SecurityGroupRule cloud read error: API action \"DescribeSecurityGroupRules\" for service \"ec2\" not yet implemented or pro feature - check https://docs.localstack.cloud/aws/feature-coverage for further information"
DETAIL:  {"message":"SecurityGroupRule cloud read error: API action \"DescribeSecurityGroupRules\" for service \"ec2\" not yet implemented or pro feature - check https://docs.localstack.cloud/aws/feature-coverage for further information"}
CONTEXT:  PL/pgSQL function until_iasql_operation(iasql_operation_optype_enum,text[]) line 39 at RAISE
PL/pgSQL function iasql_cloud_manipulation(iasql_operation_optype_enum) line 5 at assignment
PL/pgSQL function iasql_apply() line 3 at RETURN QUERY
```
Which is a bit strange because [this link](https://docs.localstack.cloud/localstack/coverage/#ec2) says it's implemented (and not a pro feature).

**Comment by dfellis** [comment]
Are you sure? The error is about `DescribeSecurityGroupRules` which doesn't appear to be in their list (while `DescribeSecurityGroups` is, which I think you accidentally latched onto)?

![Screenshot from 2022-08-17 16-15-18](https://user-images.githubusercontent.com/765551/185244643-b5f16443-a078-4e49-a56d-7b41d74cfc88.png)

![Screenshot from 2022-08-17 16-15-28](https://user-images.githubusercontent.com/765551/185244668-8d05dbb1-80ed-4ece-b3ad-4cd6f49cd31a.png)

**Comment by mtp1376** [comment]
Since the coverage of the AWS API by LocalStack is partial (it doesn't support `DescribeSecurityGroupRules` for example, which surely will happen in other services as well), quoting David:
> I think the answer for now is to just table this for now and re-eval in a few months. We don't have the bandwidth to tackle two big AWS API projects.

**Comment by dfellis** [comment]
Yep, closing as completed. :)
