### ISSUE TITLE
Implement `aws_api_gateway`

### ISSUE THREAD

**Issue by depombo** [iasql/iasql-engine#1084]

**Comment by depombo** [comment]
Currently paused since the default rate limiter for API of `api_gateway` is below 1 per second for certain endpoints. Delete is 1 request every 30 seconds per account. https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html

**Comment by depombo** [comment]
API gateway is supported by the cloud control API. We did an evaluation on it some time ago - https://github.com/iasql/iasql-engine/pull/343/files#diff-66957467e5df44140fe1d9bf8c53b06bbe765b4bc26a9202f56a937a76b75f3f. We should test if cloud control has the same API limits as the SDK https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_ApiGateway.html

**Comment by mtp1376** [comment]
Quoting from Yolanda's message on Discord:
> seems that the investigation stops soon: 
```An error occurred (UnsupportedActionException) when calling the CreateResource operation: The resource AWS::ApiGateway::RestApi is not yet supported via Cloud Control API```
those are the resources currently supported: https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/supported-resources.html

So CloudControl can't help us with the rate-limit issue here.
