### ISSUE TITLE
Upgrading can fail if there is a concurrent query on the database

### ISSUE THREAD

**Issue by dfellis** [iasql/iasql-engine#1090]
![Screenshot from 2022-08-09 08-33-25](https://user-images.githubusercontent.com/765551/183672224-cbf62d66-a54f-44cc-8c00-ac3b86046db8.png)

Particularly if there's a query involving one of the `iasql_functions`, which could be triggered by the 30-second polling the dashboard performs on all databases while it is running. If a database is in the process of being upgraded, we should simply block requests to `/run`.

One possible solution is to have an `isUpgrading` flag on the database table in the metadata database. This would require two DB queries per desired query, but since the workers are stateless, this seems unavoidable?

**Comment by aguillenv** [comment]
It failed again on upgrade with this error message, now it is a deadlock

<img width="882" alt="image" src="https://user-images.githubusercontent.com/5898639/184832373-58c82b4d-3cb5-4e65-9f0a-f402c4592ac8.png">

**Comment by aguillenv** [comment]
this is the other error that occurred today.

<img width="891" alt="image" src="https://user-images.githubusercontent.com/5898639/184833153-4b1898d8-1d96-477f-b532-e6c876738848.png">

**Comment by aguillenv** [comment]
and another deadlock

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/5898639/184833466-c3956f47-4859-4cf3-8a2f-038070cd23c5.png">
