### ISSUE TITLE
Normalize and handle AWS JSON policies comparison

### ISSUE THREAD

**Issue by depombo** [iasql/iasql-engine#1117]
Look at what Terraform does here

**Comment by depombo** [comment]
https://github.com/iasql/iasql-engine/issues/1137 should give us some ideas about how to best move forward here

**Comment by mtp1376** [comment]
Can we put some examples of the JSON policies that look different but are treated by AWS as the same? To make it easier to follow what should be fixed.

**Comment by depombo** [comment]
@ajejoseph22 keep https://github.com/iasql/iasql-engine/issues/1137#issuecomment-1230583267 in mind

**Comment by ajejoseph22** [comment]
closed by https://github.com/iasql/iasql-engine/pull/1185
