### ISSUE TITLE
Implement custom functions RFC

### ISSUE THREAD

**Issue by depombo** [iasql/iasql-engine#1192]

**Comment by aguillenv** [comment]
Creation phase:
- [ ] Add the new `iasql_rpc` entity and scheduler task
- [ ] Add the `rpc` type and behaviours to the Module interfaces
- [ ] Add the `sql` type and behaviours to the Module interfaces
- [ ] Copy the `iasql.ts` functions into the `iasql_functions` module, drop the `iasql_operation`-based handwritten functions, and expose the new ones via RPC
- [ ] Port all hand-edited migration files to use the new `sql` sub-object instead
- [ ] Add `iasql_rpc` auto-vacuum

Cleanup phase (~1 month after creation phase is done):
- [ ] Drop duplicated functions out of `iasql.ts`
- [ ] Drop the old scheduler `operation` logic
