### ISSUE TITLE
Add a file/object list table to `aws_s3` module

### ISSUE THREAD

**Issue by depombo** [iasql/iasql-engine#1231]
Each listed file in the table should have a foreign key to `bucket` in `aws_s3`. We should try to follow the same convention as the ACM modules. Perhaps simply be able to list and delete, but not upload for the first pass?

**Comment by aguillenv** [comment]
it could be possible candidate having the table to list/delete and the functions to create/update?

**Comment by dfellis** [comment]
So I figured a table would be good for listing files and their attributes (with the ability to mutate those attributes the normal IaSQL way), but reading/writing file data would be custom functions.
