### ISSUE TITLE
`iasql_upgrade` is not setting the default region

### ISSUE THREAD

**Issue by aguillenv** [iasql/iasql-engine#1239]
After upgrading using the dashboard this is the result for the query to look for the default region:

![image](https://user-images.githubusercontent.com/5898639/189109028-db52c620-ce6d-4e40-9105-6ad247f0bec5.png)

**Comment by depombo** [comment]
I think this got fixed with https://github.com/iasql/iasql-engine/pull/1241. Can you confirm @dfellis?

**Comment by depombo** [comment]
I think this is the case, feel free to re-open if this is not the case
