### ISSUE TITLE
Multi-region support in all modules

### ISSUE THREAD

**Issue by depombo** [iasql/iasql-engine#1260]

**Comment by depombo** [comment]
Follow up to https://github.com/iasql/iasql-engine/issues/1191

**Comment by aguillenv** [comment]
[x] aws_account
[ ] aws_acm_import
[ ] aws_acm_list
[ ] aws_acm_request
[x] aws_api_gateway
[x] aws_appsync
[ ] aws_cloudfront
[ ] aws_cloudwatch
[x] aws_dynamo
[ ] aws_ec2
[ ] aws_ec2_metadata
[ ] aws_ecr (Alejandro)
[ ] aws_ecs_fargate
[ ] aws_ecs_simplified
[x] aws_elasticache
[ ] aws_elb
~~[ ] aws_iam~~ [global module 🌎]
[ ] aws_lambda
[ ] aws_memory_db
[ ] aws_rds
~~[ ] aws_route53_hosted_zones~~ [global module 🌎]
[ ] aws_s3 [weird behaviour on buckets to be aware ⚠️] 
[x] aws_secrets_manager
[ ] aws_security_group
[ ] aws_vpc
~~[ ] iasql_functions~~
~~[ ] iasql_platform~~

**Comment by depombo** [comment]
This will also require a minor change to the dashboard to change reference to `region` to `default region`
