### ISSUE TITLE
How-to guide to install all AWS modules

### ISSUE THREAD

**Issue by depombo** [iasql/iasql-engine#1262]
This might change with multi-region

**Comment by aguillenv** [comment]
The idea is a "How-to" guide with just the SQL to install all modules or it makes sense to create a guide on how to manage modules in general? Showing the `iasql_modules()`, `iasql_installed_modules()`, `iasql_install()` and `iasql_uninstall()` methods?

**Comment by aguillenv** [comment]
I leave here the query to install/uninstall all modules: `select iasql_install(variadic array(select module_name from iasql_modules_list()))`

**Comment by depombo** [comment]
Yes! Though I think @dfellis had something in mind to make the query even simpler?

**Comment by depombo** [comment]
Closed in favor of https://github.com/iasql/dashboard/issues/280
