### ISSUE TITLE
Support attaching existing policies or permissions to IAM users

### ISSUE THREAD

**Issue by depombo** [iasql/iasql-engine#1328]
Similarly to https://github.com/iasql/iasql-engine/blob/main/src/modules/0.0.21/aws_iam/entity/role.ts#L34

**Comment by yrobla** [comment]
There is no policies for IAM users. I will need to add the PermissionsBoundary entity: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-iam/interfaces/attachedpermissionsboundary.html#permissionsboundaryarn
