### ISSUE TITLE
Add timeout to ELB schema

### ISSUE THREAD

**Issue by depombo** [iasql/iasql-engine#1514]

**Comment by dfellis** [comment]
Digging into this, there are two methods involved:

[DescribeLoadBalancerAttributes](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-elastic-load-balancing-v2/classes/describeloadbalancerattributescommand.html) and [ModifyLoadBalancerAttributes](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-elastic-load-balancing-v2/classes/modifyloadbalancerattributescommand.html)

The [set of attributes](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-elastic-load-balancing-v2/interfaces/loadbalancerattribute.html) is fixed, so it may make sense to create a `LoadBalancerAttributes` mapper that is auto-populated for load balancers, but how to handle `delete` is complicated. If you delete it and also delete the load balancer it's related to, it should go through, but if you delete it and not the load balancer record, it should probably restore it? It would also be unclear to end users that the attributes would be auto-generated for the user on creation of the load balancer and don't need to be defined here.

That implies it may be easier to make it an `attributes` property that is a nullable JSON and/or a [composite type](https://www.postgresql.org/docs/current/rowtypes.html), though the latter may not be supported by TypeORM, need to investigate.

**Comment by yrobla** [comment]
I'm trying something like that, just a json with all the attributes. What i found is that AWS is adding some default values if not set, so the logic needs to handle that

**Comment by yrobla** [comment]
```        attributes: [
          { Key: 'access_logs.s3.enabled', Value: 'false' },
          { Key: 'access_logs.s3.bucket', Value: '' },
          { Key: 'access_logs.s3.prefix', Value: '' },
          { Key: 'idle_timeout.timeout_seconds', Value: '60' },
          { Key: 'deletion_protection.enabled', Value: 'false' },
          { Key: 'routing.http2.enabled', Value: 'true' },
          {
            Key: 'routing.http.drop_invalid_header_fields.enabled',
            Value: 'false'
          },
          {
            Key: 'routing.http.xff_client_port.enabled',
            Value: 'false'
          },
          {
            Key: 'routing.http.preserve_host_header.enabled',
            Value: 'false'
          },
          {
            Key: 'routing.http.xff_header_processing.mode',
            Value: 'append'
          },
          {
            Key: 'routing.http.desync_mitigation_mode',
            Value: 'defensive'
          },
          { Key: 'waf.fail_open.enabled', Value: 'false' },
          {
            Key: 'routing.http.x_amzn_tls_version_and_cipher_suite.enabled',
            Value: 'false'
          }
        ],```
