### ISSUE TITLE
Fix doc scripts

### ISSUE THREAD

**Issue by dfellis** [iasql/iasql-engine#1615]
The iasql refactor has broken the documentation generation scripts, as only one version of IaSQL exists in the repo at a time, instead of a rolling window. The doc scripts need to be fixed to handle this (mostly simplified).

**Comment by mtp1376** [comment]
@dfellis Seems like the `yarn build` and `yarn start` are working under the `docs/` directory. I think I'm misunderstanding the descriptions for this issue. Can you please clarify a bit?

**Comment by dfellis** [comment]
So I'm not sure I should have made this a separate task last night. I'm referring to the Doc changes the `.version.sh`, `.drop.sh`, and `.develop.sh` scripts make. (Likely the drop and develop scripts are gonna go away entirely and only the version script sticks around.)

**Comment by depombo** [comment]
well, actually this needs to drop versions in docs entirely. This greatly simplifies the docs and is the usage Docusaurus even recommends.

**Comment by mtp1376** [comment]
I also concur with @depombo's suggestion to drop the versioning in docs.

**Comment by depombo** [comment]
I dropped all versions except for the active one so closing this out for now
