### ISSUE TITLE
Engine should upgrade databases on startup if necessary

### ISSUE THREAD

**Issue by dfellis** [iasql/iasql-engine#1619]
The `docker-entrypoint.sh` script should run a script to upgrade existing databases if necessary before spinning up the full engine.

This should be a revival of the commented-out `iasql_upgrade` code, plus some extra wrapper logic to iterate over all databases listed in the `iasql_metadata` database, but now would probably live in the `src/scripts` directory.

**Comment by depombo** [comment]
We should also figure out a way to move over the `iasql_audit` on automatic upgrade. This might be its own follow-up task though.

**Comment by dfellis** [comment]
Both done!
