### ISSUE TITLE
`repository.cloud.delete` Error Causing CI to Fail

### ISSUE THREAD

**Issue by mtp1376** [iasql/iasql-engine#1658]
Example failure:
https://github.com/iasql/iasql-engine/actions/runs/3676791338/jobs/6217939436#step:7:17205

Reason:
https://github.com/iasql/iasql-engine/blob/6a2c10003da4fcf24a1712b8f5d5cd8eb44a4748/src/modules/aws_ecr/index.ts#L629
But there's no `repositoryName` on `RepositoryPolicy`:
https://github.com/iasql/iasql-engine/blob/6a2c10003da4fcf24a1712b8f5d5cd8eb44a4748/src/modules/aws_ecr/entity/repository_policy.ts#L8-L44

**Comment by aguillenv** [comment]
but `id` is a string, and what is saying is that the first element of the string array splitter is the repository name. In the construction of the `id` string it is using the `repository.repositoryName`, right?

**Comment by mtp1376** [comment]
> but `id` is a string, and what is saying is that the first element of the string array splitter is the repository name. In the construction of the `id` string it is using the `repository.repositoryName`, right?

This is the line triggering that bug:
https://github.com/iasql/iasql-engine/blob/6a2c10003da4fcf24a1712b8f5d5cd8eb44a4748/src/modules/aws_ecr/index.ts#L548

**Comment by aguillenv** [comment]
Oh I see, yes, so the problem is in that line you have shared. Instead of
`const policy = await this.module.repositoryPolicy.db.read(ctx, this.entityId(e));`

Should be something like:
` const policy = await this.module.repositoryPolicy.db.read(ctx, this.module.repositoryPolicy.generateId({ repositoryName: e.repositoryName, region: e.region }));`

**Comment by mtp1376** [comment]
> Oh I see, yes, so the problem is in that line you have shared. Instead of `const policy = await this.module.repositoryPolicy.db.read(ctx, this.entityId(e));`
> 
> Should be something like: ` const policy = await this.module.repositoryPolicy.db.read(ctx, this.module.repositoryPolicy.generateId({ repositoryName: e.repositoryName, region: e.region }));`

I think `this.entityId(e)` can do it as well. But in here:
https://github.com/iasql/iasql-engine/blob/6a2c10003da4fcf24a1712b8f5d5cd8eb44a4748/src/modules/aws_ecr/index.ts#L628-L639
We need to change the input id to not expect a `repositoryName` because that column has been dropped and the join is being done using the target entity id (`repository_id`)
