### ISSUE TITLE
ResourceRecordsSets not deleted before HostedZone makes "Pre-clean Test Account" job fail

### ISSUE THREAD

**Issue by mtp1376** [iasql/iasql-engine#1721]
Examples:
- https://github.com/iasql/iasql-engine/actions/runs/3763114831/jobs/6396406787#step:7:14276

**Comment by aguillenv** [comment]
`ERROR:  Error: HostedZone cloud delete error: The specified hosted zone contains non-required resource record sets and so cannot be deleted.`

Another example:
https://github.com/iasql/iasql-engine/actions/runs/3821846846/jobs/6501437111

Account: 29
Region: ap-south-1

**Comment by mtp1376** [comment]
We should also include the full error and description for the future errors, since the CI logs are deleted from time to time:
<img width="787" alt="image" src="https://user-images.githubusercontent.com/5357435/212145209-03b1a72b-d441-4213-a24c-4d9308eb7c12.png">
