### ISSUE TITLE
README.md header image isn't shown

### ISSUE THREAD

**Issue by mtp1376** [iasql/iasql-engine#1805]
![Image](https://user-images.githubusercontent.com/5357435/213170159-e74bdd4c-bae7-407d-8793-69199c1f3ee5.png)

**Comment by aguillenv** [comment]
It does work for me 
![image](https://user-images.githubusercontent.com/5898639/213175770-5699347e-64cd-476a-a70e-0bced5dce214.png)

**Comment by mtp1376** [comment]
> It does work for me ![image](https://user-images.githubusercontent.com/5898639/213175770-5699347e-64cd-476a-a70e-0bced5dce214.png)

Did you try reloading + deletion of cache?

Windows 10 + Latest Chrome:
<img width="918" alt="image" src="https://user-images.githubusercontent.com/5357435/213212478-19f7c556-2497-4bb2-99b3-c02516591764.png">

Mac + Latest version of Safari:
<img width="920" alt="image" src="https://user-images.githubusercontent.com/5357435/213212659-9332c315-a7d6-43ee-a2df-286ff566d202.png">

Both tested on BrowserStack.
