### ISSUE TITLE
Duplicated engine versions installing RDS module

### ISSUE THREAD

**Issue by aguillenv** [iasql/iasql-engine#372]
Review API response and define if it is a duplication or if we are missing a property.

https://cdn.discordapp.com/attachments/920885549668114472/936109468603789312/Screenshot_from_2022-01-26_22-04-32.png

https://cdn.discordapp.com/attachments/920885549668114472/936110306889981962/Screenshot_from_2022-01-26_22-07-52.png

https://cdn.discordapp.com/attachments/920885549668114472/936111120245207050/Screenshot_from_2022-01-26_22-11-05.png

**Comment by dfellis** [comment]
No longer relevant. We don't have the table in question.
