### ISSUE TITLE
Increase reliability: testing `install` and `sync`

### ISSUE THREAD

**Issue by depombo** [iasql/iasql-engine#428]
- [x] #510
- [x] test `sync`
- [x] use random region per test suite run. maybe use isolation for `install` and `sync`
- [x] re-use the load balancer for the ecs test suite

**Comment by aguillenv** [comment]
Taking this over.

> * [ ]  test `install`/`uninstall` Including interactions between installing and uninstalling other modules
> * [ ]  test `sync`
> * [x]  use random region per test suite run. maybe use isolation for `install` and `sync`
> * [x]  re-use the load balancer for the ecs test suite

**Comment by aguillenv** [comment]
Sync tested withhttps://github.com/iasql/iasql-on-iasql/pull/21
