### ISSUE TITLE
Safer `sync` and faster `apply`

### ISSUE THREAD

**Issue by depombo** [iasql/iasql-engine#459]
Fire triggers on `INSERT`s and `UPDATE`s to keep track of changes in some sort of system table. `apply` goes off these changes and `sync` won't run if there are pending changes unless there is some sort of `force` flag.

**Comment by depombo** [comment]
Depends on #469

**Comment by depombo** [comment]
Probably something like
- [ ] Triggers on all our tables that inserts into a `staged_changes` table https://dba.stackexchange.com/questions/241173/postgresql-trigger-to-keep-track-of-table-changes
- [ ] Have the `iasql` service in the engine go off this table

**Comment by depombo** [comment]
> * [ ]  Triggers on all our tables that inserts into a `iasql_staged_changes` table https://dba.stackexchange.com/questions/241173/postgresql-trigger-to-keep-track-of-table-changes

Maybe we can do something like this to automate this https://www.githubstatus.com

**Comment by depombo** [comment]
We should keep this reddit discussion in mind https://www.reddit.com/r/devops/comments/u3b3wf/comment/i4o89s9/. Apparently Pulumi by default does not check the state of the cloud as this issue is suggesting we do, while Terraform does.

We need this for things like ASG and Spot in EC2, but perhaps we might not want to rely on this for that to work in case the user always wants to use the `force`/`refresh` flag all the time?

**Comment by dfellis** [comment]
> We should keep this reddit discussion in mind https://www.reddit.com/r/devops/comments/u3b3wf/comment/i4o89s9/. Apparently Pulumi by default does not check the state of the cloud as this issue is suggesting we do too, while Terraform always does.
> 
> We need this for things like #960 in EC2, but perhaps we might not want to rely on this for that to work in case the user always wants to use the `force`/`refresh` flag all the time?

I think this is a partial misunderstanding of what we intend to do here? We still need to check the cloud state for each record we saw changed, which is equivalent to Terraform. What we currently do is a full check of everything in their cloud every time, which this eliminates.

**Comment by depombo** [comment]
Ah! I think I get it 👍
