### ISSUE TITLE
Blocking stored procedures for iasql operations

### ISSUE THREAD

**Issue by depombo** [iasql/iasql-engine#468]
Depends on the cron from https://github.com/iasql/iasql-engine/issues/469 and some sort of table to poll on. Unblocks migration systems that only support SQL.

Add blocking stored procedures that can replace the CLI commands, `CALL iasql-${cli-command}` SPs. Use a loop with `pg_sleep()`. Necessary to display output on `apply` and to make sure the migrations don't error on missing tables for `install`/`uninstall`

**Comment by depombo** [comment]
We could give a precise timestamp to `CALL iasql_apply(timestamp)` that schedules an `apply` and then polls with `pg_sleep` an `iasql_ops` table for a row where the primary key is the provided timestamp. Once the row shows up polling stops. The row will have an output field that is then printed by the stored procedure. The `iasql_ops` table will look something like:

```
CREATE TABLE iasql_ops (
   timestamp ??
   iasql_op ENUM
   output TEXT
)
```

**Comment by aguillenv** [comment]
We could probably:
1. Generate a unique id `uuid` and give it as a param to the graphile_worker job to schedule an apply. This could be the primary key. This could also let us track which operations are being executed for this apply.
2. `apply` inserts a new row and start a `start_date`. 
3. The scheduler starts looping with `pg_sleep` and poll the table asking for an `end_date`

```sql
CREATE TABLE iasql_apply (
   uuid UUID
   start_date TIMESTAMP
   end_date TIMESTAMP
   output TEXT
   error TEXT
)
```

4.  When `apply` is done, update the row with the `uuid` of the operation and sets the `end_date`.

This way we can track all operations, even if they are a no-op.

We would also have the `iasql_change` or something like that that it will be the table with the `timestamps` of all the changes every time a mutation occur and to define if we need to run the apply. for all those changes that need to be executed we could update a column to point the `uuid` that executed them. This could be refined in the future and help us with logs and traceability maybe?

the `iasql_change` would be something like:
```sql
CREATE TABLE iasql_change (
   timestamp TIMESTAMP
   action ENUM (<insert/update/delete>_<table-name>)
   apply_uuid FK_ iasql_apply
)
```

**Comment by depombo** [comment]
That sounds great, I like your suggestion to use a uuid a lot!
