### ISSUE TITLE
Add `iasql export` data-only flag

### ISSUE THREAD

**Issue by depombo** [iasql/iasql-engine#480]
Then modify how-to guide to version control existing infrastructure.

Also add a guide to see what existing resources you have in your AWS account once you connect it to IaSQL run the following query to display
tables with non-zero rows:

```sql
psql postgres://d0va6ywg:nfdDh#EP4CyzveFr@db.iasql.com/_4b2bb09a59a411e4
_4b2bb09a59a411e4 =#
  SELECT schemaname,relname,n_live_tup 
    FROM pg_stat_user_tables 
  ORDER BY n_live_tup DESC;
```

**Comment by dfellis** [comment]
Why do we want it to export data only? You can't load that into a local Postgres for testing purposes then?

**Comment by depombo** [comment]
it can be flag too in order to have the data to put into an initial migration, though that migration has to be marked as "done" somehow?

**Comment by dfellis** [comment]
I see. You're thinking about something like Django or Prisma where it can import the current schema into the migration system but not the data within it.

The SQL we can generate with a `--data-only` export command could use the [`ON CONFLICT`](https://www.postgresqltutorial.com/postgresql-upsert/) (specifically `ON CONFLICT DO NOTHING`) syntax to turn it into an "upsert" and then the migration will run successfully, properly represent the data in the database, and not alter the database.

**Comment by depombo** [comment]
flags to use on `pg_dump`: `--data-only, --column-inserts, --rows-per-insert=25, --on-conflict-do-nothing`
