### ISSUE TITLE
Fix ec2 module

### ISSUE THREAD

**Issue by depombo** [iasql/iasql-engine#606]
Currently the module does not provide update/replace determination and has a few mapper calls that are not awaited but somehow test suite passes

**Comment by dfellis** [comment]
WRT the mapper calls that aren't `await`ed, I can only find one:

![Screenshot from 2022-04-07 11-17-34](https://user-images.githubusercontent.com/765551/162250243-de699910-2277-4cbb-8c68-a4ca89e0071f.png)

But it actually is, if a bit weird. The async function calls the create async function without an `await` which means the `created` variable is a Promise. Then it calls the delete async function and does `await` it, and then finally returns the promise. This means that the code actually schedules both async functions in parallel and then the returned promise is passed through to the caller (which is what all `async` functions do under the hood. They return promises for the caller to resolve on their own with either a `.then` or an `await`) so the `create` call *is* properly resolved by the caller of this async function, and there's actually no issues, despite it looking a bit weird.

The other part should be pretty easy to fix, though :)
