### ISSUE TITLE
Error retrieving vpc 

### ISSUE THREAD

**Issue by aguillenv** [iasql/iasql-engine#648]
https://sentry.io/organizations/iasql/issues/3186398059/?project=6106929&referrer=webhooks_plugin

Seems to be failing on target group mapper setting up the vpc. Maybe the vpc does not exists?  Is it a wrong string?

**Comment by dfellis** [comment]
I'm pretty certain we have fixed this. It was a bug in ELB accidentally attaching multiple VPCs to the singular vpc property and then exploding. Getting stricter with our types should help avoid this class of bug in the future.
