### ISSUE TITLE
Database connection collision

### ISSUE THREAD

**Issue by aguillenv** [iasql/iasql-engine#718]
Apparently it occurred during `/connect`
https://sentry.io/organizations/iasql/issues/3239613744/events/4a43547b1e414f99a3f64e80c39d7bc3/?project=6106929

```
Error: Connection database-172713 already exists
```

**Comment by dfellis** [comment]
I actually ran into that once in the test suite, too. There's just not enough entropy in that Math.random call to actually avoid collisions. Might make more sense to just switch the connection IDs to `uuid`s?

**Comment by aguillenv** [comment]
> I actually ran into that once in the test suite, too. There's just not enough entropy in that Math.random call to actually avoid collisions. Might make more sense to just switch the connection IDs to `uuid`s?

probably that'd be the best solution
