### ISSUE TITLE
Error reinstalling a module instead of ignoring it

### ISSUE THREAD

**Issue by aguillenv** [iasql/iasql-engine#876]

**Comment by dfellis** [comment]
I don't think this should be changed. If it errors on install when there's nothing to do, then you can't write reusable scripts (for the button concept or otherwise) because there's no easy way to know if the database already has the required modules or not.

**Comment by dfellis** [comment]
So... https://github.com/iasql/iasql-engine/blob/main/src/services/iasql.ts#L794-L797

We already do that? We need to figure out why that failed for you. Was that in a staging DB or a production DB?
