### ISSUE TITLE
Install/sync error when connecting an AWS account with ReadOnly Access

### ISSUE THREAD

**Issue by depombo** [iasql/iasql-engine#949]

**Comment by aguillenv** [comment]
@depombo what privileges did you used to test this? I have tested the following and worked for me:

1. Created a user with `ReadOnlyAccess` AWS Managed Policy ![Image](https://user-images.githubusercontent.com/5898639/177952690-dca708fa-1851-49b4-99dc-cd97928d62ca.png)
2. Connect using its credentials
3. Installed modules
4. Apply failed as expected: ![Image](https://user-images.githubusercontent.com/5898639/177953003-c219ffbf-4c02-4fd2-91cf-d7f52f0c64fd.png)
5. Sync correctly: ![Image](https://user-images.githubusercontent.com/5898639/177953718-05b58294-8a1e-4dd5-b7b0-a7c653556bb3.png)

**Comment by depombo** [comment]
Closing this out as the real issue was pointed out by @aguillenv in https://github.com/iasql/iasql-engine/issues/950
